apiVersion: v1
kind: Service
metadata:
  name: mysql-production
spec:
  selector:
    app: webapp-sql-production
    tier: backend
  type: NodePort
  ports:
  - protocol: "TCP"
    port: 3306
    targetPort: 3306
    nodePort: 30008
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sqldb-production
  labels:
    app: webapp-sql-production
    tier: backend
spec:
  selector:
    matchLabels:
      app: webapp-sql-production
      tier: backend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: webapp-sql-production
        tier: backend
    spec:
      containers:
      - image: mysql
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: password
        - name: MYSQL_DATABASE
          value: dblinks
        - name: MYSQL_USER
          value: nam
        - name: MYSQL_PASSWORD
          value: password
        args: ["--default-authentication-plugin=mysql_native_password"]
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /docker-entrypoint-initdb.d
      nodeName: ip-10-0-101-19.us-east-2.compute.internal
      volumes:
      - name: mysql-persistent-storage
        configMap:
          name: mysql-initdb-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-initdb-config
data:
  initdb.sql: |
    CREATE TABLE users (
      id INT(11) NOT NULL AUTO_INCREMENT,
      username VARCHAR(16) NOT NULL,
      password VARCHAR(60) NOT NULL,
      fullname VARCHAR(100) NOT NULL,
      PRIMARY KEY (id)
    ) AUTO_INCREMENT=2;
    CREATE TABLE links (
      id INT(11) NOT NULL,
      title VARCHAR(150) NOT NULL,
      url VARCHAR(255) NOT NULL,
      description TEXT,
      user_id INT(11),
      created_at timestamp NOT NULL DEFAULT current_timestamp,
      CONSTRAINT fk_user FOREIGN KEY(user_id) REFERENCES users(id)
    );
    ALTER TABLE links
    ADD PRIMARY KEY (id);

    ALTER TABLE links
    MODIFY id INT(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT = 2;

    DESCRIBE links;